# Don't run CI for this config yet. We're not ready to move official builds on to Azure Pipelines
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- job: Helix
  timeoutInMinutes: 240
  pool:
    name: Hosted VS2017
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    clean: true
  - script: .\build.cmd -ci /t:Helix /bl:$env:BUILD_SOURCESDIRECTORY\artifacts\log\$env:BuildConfig\SendToHelix.binlog
    displayName: Run build.cmd helix target
